apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: Api
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: kaytheog/api
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password    
        livenessProbe:
          httpGet:
            path: /ok
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /ok
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1