apiVersion: apps/v1
kind: StatefulSet
metadata:
  #namespace: db
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb 
  serviceName: "mongo-db-service"
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: mongodb
        replicaset: rs0.main
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - rs0.main
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 1
      containers:
      - name: mongodb
        image: mongo:4.2
        command: 
         - "numactl"
         - "--interleave=all"
         -  "mongod"
         - "--wiredTigerCacheSizeGB" 
         - "0.1"
         - "--bind_ip" 
         - "0.0.0.0"
        ports:
        - containerPort: 27017
          name: web           
        env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:                            
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        resources:
          requests:
            cpu: 400m
            memory: 200Mi 
        volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db 

  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mongodb-class"
      resources:
        requests:
          storage: 2Gi              