apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: db
  app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb 
  serviceName: "mongo-db-service"
  replicas: 3 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo
        commands: ["numactl","--interleave=all", "mongod", "--wiredTigerCacheSizeGB",  "0.1", "--bind_ip", "0.0.0.0", "--replSet",]
        ports:
        - containerPort: 27017
          name: web           
        env:
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:                            
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mongo", "--eval", "db.adminCommand('ping')"]
          initialDelaySeconds: 5
          timeoutSeconds: 3            
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mongodb-class"
      resources:
        requests:
          storage: 1Gi              