apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: Api
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: kaytheog/api
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGODB_URL
            valueFrom: 
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password 
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom: 
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
        resources:
          requests:
            cpu: 100m
            memory: 20Mi              
        livenessProbe:
          httpGet:
            path: /ok
            port: 5000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /ok
             port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1