name: 'Building and testing of Infra and close'

on: 
  pull_request:
    branches: [main] 
  workflow_dispatch:   
  

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
     contents: read
     packages: write
     security-events: write

jobs:
  linting-dockerfile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: linting Frontend Docker file
      continue-on-error: true
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./frontend/Dockerfile  

    - name: linting Frontend Docker file
      continue-on-error: true
      uses: hadolint/hadolint-action@v2.1.0
      with:
        dockerfile: ./frontend/Dockerfile      

  backend-image-scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build the image
      working-directory: ./backend
      run: docker build . -t kaytheog/backend

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/backend
        args: --file=Dockerfile
        json: true 

  Frontend-images-scanning:    
    name: Scanning Frontend-images-scanning
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Build the image
      working-directory: ./frontend
      run: docker build . -t kaytheog/frontend 

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/frontend
        args: --file=Dockerfile
        json: true
    
  IAC-scaning:
    name: scaning Infra
    runs-on: ubuntu-latest
    steps:

     - name: Checkout the code
       uses: actions/checkout@v2
    
  Building-and-pushing-to-Docker-hub:

    needs: [backend-image-scanning, Frontend-images-scanning, linting-dockerfile]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Backend Docker image
      id: build-and-push-backend
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        push: true
        tags: kaytheog/backend

    - name: Build and push frontend Docker image
      id: build-and-push-frontend
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        push: true
        tags: kaytheog/frontend 

  
  
