name: 'Building and testing of Infra and close'

on:
  push:
    branches: [ Main ]

  

env:
  
 # AWS_REGION: eu-west-1
 # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # cat $HOME/.kube/config | base64
  # create secrets with the base64 encoded values
 # KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #KUBE_NAMESPACE: production
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}



jobs:

  Image-scanning:
    permissions:
     contents: read
     packages: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting up ...

    - name: Build a Docker image
      working-directory: ./backend
      run: docker build -t Kaytheog/backend .
    
    - name: checking  Docker image for vulnerabilities
      # Snyk can be used to break the build when it detects vulnerabilities.
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: Kaytheog/backend
        args: 
           --file=Dockerfile
           --severity-threshold=high

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif