name: 'Building and testing of Infra and close'

on:
  [push]
    #branches: [ Main ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
     contents: read
     packages: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2
    - name: setting up ...
      working-directory: ./backend
<<<<<<< HEAD
      run: docker build -t kaytheog/backend  .
=======
      run: docker build -t kaytheog/backend .
>>>>>>> 0d5725889097a6415f4bb25118e214184caf875b
      
    - name: checking  Docker image for vulnerabilities
=======
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build the image
      working-directory: ./backend
      run: docker build . -t you-image 
    - name: Run Snyk to check image for vulnerabilities
>>>>>>> 4dae01526d73121c485af6de7806a3184dcccec2
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
<<<<<<< HEAD
<<<<<<< HEAD
        image: kaytheog/backend
        args: 
           --file=Dockerfile
           --severity-threshold=high
=======
        image: Kaytheog/backend
        args: --file=Dockerfile
          # --severity-threshold=high
          # --output-file=snyk.sarif
>>>>>>> 0d5725889097a6415f4bb25118e214184caf875b

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
=======
        image: your-image
        args: --file=Dockerfile
        json: true
    - uses: garethr/snyk-to-sarif@master
    - uses: actions/upload-artifact@v2
      with:
        name: SARIF
        path: snyk.sarif
    - name: Upload the SARIF file
      uses: github/codeql-action/upload-sarif@v1
>>>>>>> 4dae01526d73121c485af6de7806a3184dcccec2
      with:
        sarif_file: snyk.sarif
