name: 'Building and testing of Infra and close'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]  

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
     contents: read
     packages: write
     security-events: write

jobs:
  image-scanning-backend-frontend-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build the image
      working-directory: ./backend
      run: docker build . -t kaytheog/backend

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/backend
        args: --file=Dockerfile
        json: true

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif    

  Frontend-images-scaning:    

    name: scan Frontend-images-scaning
    runs-on: ubuntu-latest
    steps:

    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Build the image
      working-directory: ./frontend
      run: docker build . -t kaytheog/frontend 

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/frontend
        args: --file=Dockerfile
        json: true
    
  IAC-scaning:
    name: scaning Infra
    runs-on: ubuntu-latest
    steps:

     - name: Checkout the code
       uses: actions/checkout@v2
    

  Building-and-pushing-to-Docker-hub:

    needs: [image-scanning-backend-frontend-infra, Frontend-images-scaning]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
    - name: Build and push Backend Docker image
      id: build-and-push-backend
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        push: true
        tags: kaytheog/backend

    - name: Build and push frontend Docker image
      id: build-and-push-frontend
      uses: docker/build-push-action@v3
      with:
        context: ./frontend
        push: true
        tags: kaytheog/frontend 

  
  
