name: 'Building and testing of Infra and close'

on:
  [push]
    #branches: [ Main ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
     contents: read
     packages: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build the image
      working-directory: ./backend
      run: docker build . -t kaytheog/backend

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: your-image
        args: --file=Dockerfile
        json: true


