name: 'Building and testing of Infra and close'

on:
  [push]
    #branches: [ Main ]

env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
     contents: read
     packages: write

jobs:
  image-scanning-backend-frontend-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build the image
      working-directory: ./backend
      run: docker build . -t kaytheog/backend

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/backend
        args: --file=Dockerfile
        json: true
      
    - name: Build the image
      working-directory: ./frontend
      run: docker build . -t kaytheog/frontend 

    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: kaytheog/frontend
        args: --file=Dockerfile
        json: true
   



  Building-and-pushing-to-Docker-hub:
    needs: image-scanning-backend-frontend-infra
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Build Docker image
      working-directory: ./backend
      run: docker build kaytheog/backend .

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: kaytheog/backend
     

    - name: Build Docker image
      working-directory: ./Frontend
      run: Docker build kaytheog/backend .

  
