name: 'Infra Scanning'

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   
  
permissions:
  contents: read 


jobs:
  Infra Scanning-with-snyk:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}  