name: 'Infra Scanning'

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   
  
env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

permissions:
  contents: read 


jobs:
  security-scanning-kubernetes-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check Kubernetes manifest for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./kubernetes-deployment-manifest
          args: --severity-threshold=high

  security-scanning-Infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk terraform file for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./eks-cluster
          args: --severity-threshold=high
